### ISSUE TITLE
thanks for your repo, but the enhancement.py and the test.py are empty.

### ISSUE THREAD

**Issue by LucySha** [haoxiangsnr/Wave-U-Net-for-Speech-Enhancement#3]

**Comment by haoxiangsnr** [comment]
I will add it in next week.

**Comment by LucySha** [comment]
@haoxiangsnr 非常感谢您的回复！在创建环境的时候，我遇到了由于版本导致的问题，目前我的版本为：python3.6 cudnn=7.6 cudatoolkit=10.0 tensorflow-gpu=1.14.0(使用conda默认创建最新版本)， 能提供一下相关依赖的具体版本吗？

**Comment by haoxiangsnr** [comment]
Added.
