### ISSUE TITLE
training SNR

### ISSUE THREAD

**Issue by lvyilan23** [haoxiangsnr/Wave-U-Net-for-Speech-Enhancement#4]
请问这个是UNetGAN论文中使用的baseline吗？这个模型的训练SNR是和原文一样吗，还是和UNetGAN一样，使用-15&-10&-5&0dB呢？

**Comment by haoxiangsnr** [comment]
1. 是的
2. 项目主页截图中的这组实验信噪比为-15dB，-10dB，-5dB与0dB，数据集为TIMIT，噪声种类忘记了。数据量整体更大些。

**Comment by wbjnpu** [comment]
> 1. 是的
> 2. 项目主页截图中的这组实验信噪比为-15dB，-10dB，-5dB与0dB，数据集为TIMIT，噪声种类忘记了。数据量整体更大些。

噪声是加性噪声这么加上去的么

**Comment by haoxiangsnr** [comment]
是的，可以参考 MS-SNSD 中的做法：https://github.com/microsoft/MS-SNSD
